/// this file was 100% generated by gemini 3.8 flash
use std::path::Path;
use std::time::Instant;
use std::{env, eprintln, println, vec};

use image::{GrayImage, Luma, imageops};
use selfnn::layer::{Linear, ReLU, Softmax};

#[allow(unused_imports)]
use selfnn::mnist::{load_mnist_images, render_ascii};
use selfnn::model::Sequential;
use selfnn::tensor::Tensor;

fn preprocess_image(path: &str) -> Result<(Tensor, GrayImage), Box<dyn std::error::Error>> {
    let mut img = image::open(path)?.to_luma8();
    let (w, h) = img.dimensions();

    // 1. Invert colors if background is light (check the 4 corner pixels)
    let corner_sum = img.get_pixel(0, 0)[0] as u32
        + img.get_pixel(w - 1, 0)[0] as u32
        + img.get_pixel(0, h - 1)[0] as u32
        + img.get_pixel(w - 1, h - 1)[0] as u32;
    let invert = (corner_sum / 4) > 128;

    // If image is already 28x28, simply invert if needed and use directly
    if w == 28 && h == 28 {
        let mut canvas = GrayImage::new(28, 28);
        let mut data = Vec::with_capacity(784);
        for y in 0..28 {
            for x in 0..28 {
                let mut val = img.get_pixel(x, y)[0];
                if invert {
                    val = 255 - val;
                }
                canvas.put_pixel(x, y, Luma([val]));
                data.push(val as f32 / 255.0);
            }
        }
        return Ok((Tensor::new(data, (1, 784)), canvas));
    }

    // 2. Find bounding box of the ink strokes
    let mut min_x = w;
    let mut max_x = 0;
    let mut min_y = h;
    let mut max_y = 0;

    for y in 0..h {
        for x in 0..w {
            let mut val = img.get_pixel(x, y)[0];
            if invert {
                val = 255 - val;
                img.put_pixel(x, y, Luma([val]));
            }
            if val > 30 {
                min_x = min_x.min(x);
                max_x = max_x.max(x);
                min_y = min_y.min(y);
                max_y = max_y.max(y);
            }
        }
    }

    // Handle edge case: blank image
    if min_x > max_x || min_y > max_y {
        let blank_canvas = GrayImage::new(28, 28);
        return Ok((Tensor::zeros((1, 784)), blank_canvas));
    }

    // 3. Crop bounding box
    let crop_w = (max_x - min_x + 1).max(1);
    let crop_h = (max_y - min_y + 1).max(1);
    let cropped = imageops::crop_imm(&img, min_x, min_y, crop_w, crop_h).to_image();

    // 4. Scale bounding box proportionally to fit within a 20x20 box (standard MNIST format)
    let scale = 20.0 / (crop_w.max(crop_h) as f32);
    let new_w = ((crop_w as f32 * scale).round() as u32).clamp(1, 20);
    let new_h = ((crop_h as f32 * scale).round() as u32).clamp(1, 20);
    let resized = imageops::resize(&cropped, new_w, new_h, imageops::FilterType::Lanczos3);

    // 5. Center into a 28x28 black canvas using Center of Mass (LeCun 1998)
    let mut sum_mass = 0.0f32;
    let mut com_x = 0.0f32;
    let mut com_y = 0.0f32;
    for y in 0..new_h {
        for x in 0..new_w {
            let val = resized.get_pixel(x, y)[0] as f32;
            if val > 30.0 {
                sum_mass += val;
                com_x += x as f32 * val;
                com_y += y as f32 * val;
            }
        }
    }

    let (start_x, start_y) = if sum_mass > 0.0 {
        com_x /= sum_mass;
        com_y /= sum_mass;
        let sx = ((13.5 - com_x).round() as i64).clamp(0, (28 - new_w) as i64);
        let sy = ((13.5 - com_y).round() as i64).clamp(0, (28 - new_h) as i64);
        (sx, sy)
    } else {
        (((28 - new_w) / 2) as i64, ((28 - new_h) / 2) as i64)
    };

    let mut canvas = GrayImage::new(28, 28);
    imageops::overlay(&mut canvas, &resized, start_x, start_y);

    // 6. Convert to 1x784 Tensor normalized to [0.0, 1.0]
    let mut data = Vec::with_capacity(784);
    for p in canvas.pixels() {
        data.push(p[0] as f32 / 255.0);
    }

    Ok((Tensor::new(data, (1, 784)), canvas))
}

fn ensure_sample_image(sample_path: &str) {
    if !Path::new(sample_path).exists() && Path::new("data/t10k-images-idx3-ubyte").exists() {
        let test_x = load_mnist_images("data/t10k-images-idx3-ubyte");
        let mut img = GrayImage::new(28, 28);
        for y in 0..28 {
            for x in 0..28 {
                let pixel_val = (test_x.get(0, y * 28 + x) * 255.0) as u8;
                img.put_pixel(x as u32, y as u32, Luma([pixel_val]));
            }
        }
        let _ = img.save(sample_path);
    }
}

fn main() {
    println!("============================================================");
    println!("        MNIST Real-World Digit Classifier on selfnn         ");
    println!("============================================================");

    // Determine target image path
    let default_sample = "data/sample_digit.png";
    let image_path = match env::args().nth(1) {
        Some(path) => path,
        None => {
            println!("No image path specified.");
            println!("Usage: cargo run --release --example predict -- <path-to-image>\n");
            ensure_sample_image(default_sample);
            println!("Using default sample image: {}", default_sample);
            default_sample.to_string()
        }
    };

    if !Path::new(&image_path).exists() {
        eprintln!("Error: Image file '{}' not found!", image_path);
        std::process::exit(1);
    }

    // 1. Build Model Architecture: 784 -> 128 -> 64 -> 10 -> Softmax
    let mut model = Sequential::new(vec![
        Box::new(Linear::new(784, 128)),
        Box::new(ReLU::new()),
        Box::new(Linear::new(128, 64)),
        Box::new(ReLU::new()),
        Box::new(Linear::new(64, 10)),
        Box::new(Softmax::new()),
    ]);

    // 2. Load Pretrained Weights
    let weights_path = "data/mnist_weights.bin";
    if !Path::new(weights_path).exists() {
        eprintln!("Error: Weights file '{}' not found!", weights_path);
        eprintln!("Please train the model first: cargo run --release --example train_mnist");
        std::process::exit(1);
    }

    let start_load = Instant::now();
    model
        .load_weights(weights_path)
        .expect("Failed to load weights");
    println!("Weights loaded in {:.2?}", start_load.elapsed());

    // 3. Preprocess Image
    println!("\nPreprocessing '{}'...", image_path);
    let (input_tensor, canvas) = match preprocess_image(&image_path) {
        Ok(res) => res,
        Err(e) => {
            eprintln!("Failed to process image '{}': {}", image_path, e);
            std::process::exit(1);
        }
    };

    // Save preprocessed canvas for inspection
    let preprocessed_path = "data/preprocessed_input.png";
    if canvas.save(preprocessed_path).is_ok() {
        println!("Saved preprocessed 28x28 canvas to: {}", preprocessed_path);
    }

    // 4. Visual Terminal Inspection
    // println!("\nPreprocessed Image as seen by Neural Network (28x28):");
    // render_ascii(&input_tensor.data);

    // 5. Model Inference
    let start_infer = Instant::now();
    let pred = model.forward(&input_tensor);
    let infer_duration = start_infer.elapsed();

    // 6. Find Top Prediction & Print Confidence Distribution
    let mut best_digit = 0;
    let mut best_prob = 0.0;
    for c in 0..10 {
        let prob = pred.get(0, c);
        if prob > best_prob {
            best_prob = prob;
            best_digit = c;
        }
    }

    println!("\n╔══════════════════════════════════════════════════════╗");
    println!(
        "║  PREDICTED DIGIT: {:^2}       Confidence: {:>5.1}%        ║",
        best_digit,
        best_prob * 100.0
    );
    println!("╚══════════════════════════════════════════════════════╝");

    println!("\nConfidence Distribution:");
    for c in 0..10 {
        let prob = pred.get(0, c);
        let bar_len = (prob * 40.0).round() as usize;
        let bar: String = "█".repeat(bar_len);
        let marker = if c == best_digit { "👉" } else { "  " };
        println!("{} [{}] {:>5.1}% | {}", marker, c, prob * 100.0, bar);
    }

    println!("\nInference latency: {:.2?}", infer_duration);
}
